name: OnPushTag

#動作するトリガー（前提条件）
#masterブランチにタグ付きでpushされた場合のみ発動
on:
  push:
#    branches: [ master ]
    tags: 
      - 'v*'

#ワークフローの実行
#参考：https://proudust.github.io/20191220-create-release-with-ghactions/
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      #セットアップ
      - uses: actions/checkout@v1



      # env.RELEASE_VERSIONにバージョン名（タグ名）を代入
      - name: Set env RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      # env.REPOSITORY_NAMEにリポジトリ名を代入
      - name: Set env REPOSITORY_NAME
        run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')


      # ビルド処理(Githubからダウンロード)
      - name: Source Download
        run: |
          wget https://github.com/average34/${{ env.REPOSITORY_NAME }}/archive/${{ env.RELEASE_VERSION }}.zip -O ${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip



      #Github上でリリースを作成
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # リリースのタグ (必須)
          tag_name: ${{ github.ref }}
          # リリースのタイトル (必須)
          # リポジトリ名とタグ名を出力するように。
          release_name: ${{ env.REPOSITORY_NAME }} ${{ github.ref }}
          # リリースのタイトル (省略可能)
          body: |
            ${{ env.REPOSITORY_NAME }}の本体です。
            下の「Assets」タブを開き、「${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip」をダウンロードしてください。
            更新箇所
            v1.21

          # 下書き状態で作成する場合は true (省略時 false)
          draft: true
          # プレリリース表示を付ける場合は true (省略時 false)
          prerelease: false
      
      # リリースしたものにzipファイルを追加
      - uses: actions/upload-release-asset@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip
          asset_name: ${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip

