name: OnReleaseItch

#動作するトリガー（前提条件）
# リリースの「公開」時に発動
on:
  release:
    types: [published]


jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      #セットアップ
      - uses: actions/checkout@master

      # env.RELEASE_VERSIONにバージョン名（タグ名）を代入
      - name: Set env RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | awk -F / '{print $3}')
      # env.REPOSITORY_NAMEにリポジトリ名を代入
      - name: Set env REPOSITORY_NAME
        run: echo ::set-env name=REPOSITORY_NAME::$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
    

      # ビルド処理(Githubからダウンロード)
      - name: Source Download
        run: |
          wget https://github.com/average34/${{ env.REPOSITORY_NAME }}/archive/${{ env.RELEASE_VERSION }}.zip -O ${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip

      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: shokushu-windows
          ITCH_GAME: eraVoiceroidShokushuQ
          ITCH_USER: average34
          PACKAGE: ./${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip
          VERSION: ${{ env.RELEASE_VERSION }}
