name: Tweet Trigger Release
# リリースの「公開」時に発動
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      #セットアップ
      - uses: actions/checkout@master

      # env.RELEASE_VERSIONにバージョン名（タグ名）を代入
      - name: Set env RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | awk -F / '{print $3}')
      # env.REPOSITORY_NAMEにリポジトリ名を代入
      - name: Set env REPOSITORY_NAME
        run: echo ::set-env name=REPOSITORY_NAME::$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
      #  run: echo $GITHUB_REF

      # env.TWEET_TEXTにツイート内容を代入
      - name: Set env TWEET_TEXT_1
        run: echo ::set-env name=TWEET_TEXT_1::"eraVoiceroid触手宮 ${{ env.RELEASE_VERSION }} 更新しました。"

      - name: Set env TWEET_TEXT_2
        run: echo ::set-env name=TWEET_TEXT_2::"https://github.com/$GITHUB_REPOSITORY/releases/"

      - name: Set env TWEET_TEXT_3
        run: echo ::set-env name=TWEET_TEXT_3::"このゲームは、VOICEROID、CeVIO、AITalkのキャラクターの二次創作ゲームです。 テキストのみで進める、ボイチェビ達が触手と戦うゲームです。ぜひとも遊んでください。"

      # env.TWEET_TEXT_TESTにツイート内容を代入
      - name: Set env TWEET_TEXT_TEST
        run: echo ::set-env name=TWEET_TEXT_TEST::"${{ env.REPOSITORY_NAME }} ${{ env.RELEASE_VERSION }} \\nこれはGithub Actionsのツイートテストです。"

      #ツイートする
      #- name: Tweet to bot
      #  uses: mugi111/tweet-trigger-release@v1.2
      #  with:
      #    consumer_key: ${{ secrets.CONSUMER_KEY }}
      #    consumer_secret: ${{ secrets.CONSUMER_SECRET }}
      #    access_token_key: ${{ secrets.ACCESS_TOKEN_KEY }}
      #    access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
      #    tweet_body: ${{ env.TWEET_TEXT_TEST }}

      # Github側でsecretsを設定する必要あり
      # DISCORD_WEBHOOKにURIを代入
      - name: Set env DISCORD_WEBHOOK 1
        run: echo -e ::set-env name=DISCORD_WEBHOOK::${{ secrets.DISCORD_WEBHOOK }}

      # Discordで通知する
      - name: Discord notification1-1
        uses: Ilshidur/action-discord@master
        with:
            args: ${{ env.TWEET_TEXT_1 }}
      - name: Discord notification1-2
        uses: Ilshidur/action-discord@master
        with:
            args: ${{ env.TWEET_TEXT_2 }}
#      - name: Discord notification1-3
#        uses: Ilshidur/action-discord@master
#        with:
#            args: ${{ env.TWEET_TEXT_3 }}

      # DISCORD_WEBHOOKにURIを代入
      - name: Set env DISCORD_WEBHOOK for BOIRODA
        run: echo -e ::set-env name=DISCORD_WEBHOOK::${{ secrets.DISCORD_WEBHOOK_BOIRODA }}

      # Discordで通知する
      - name: Discord notification2-1
        uses: Ilshidur/action-discord@master
        with:
            args: ${{ env.TWEET_TEXT_1 }}
      - name: Discord notification2-2
        uses: Ilshidur/action-discord@master
        with:
            args: ${{ env.TWEET_TEXT_2 }}
#      - name: Discord notification2-3
#        uses: Ilshidur/action-discord@master
#        with:
#            args: ${{ env.TWEET_TEXT_3 }}


# [EOF]